//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltors.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPreferences
    {
        public int PreferenceID { get; set; }
        public int ClientID { get; set; }
        public string PropertyType { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinArea { get; set; }
        public Nullable<decimal> MaxArea { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
