//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltors.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deals()
        {
            this.DealDocuments = new HashSet<DealDocuments>();
        }
    
        public int DealID { get; set; }
        public int PropertyID { get; set; }
        public int ClientID { get; set; }
        public int RealtorID { get; set; }
        public string DealType { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public decimal DealAmount { get; set; }
        public string DealStatus { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealDocuments> DealDocuments { get; set; }
        public virtual Users Users { get; set; }
        public virtual Properties Properties { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
