//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltors.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealDocuments
    {
        public int DealDocumentID { get; set; }
        public int DealID { get; set; }
        public int TemplateID { get; set; }
        public string DocumentContent { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
    
        public virtual Deals Deals { get; set; }
        public virtual DocumentTemplates DocumentTemplates { get; set; }
    }
}
