//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltors.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestProperties
    {
        public int RequestPropertyID { get; set; }
        public int RequestID { get; set; }
        public int PropertyID { get; set; }
    
        public virtual Properties Properties { get; set; }
        public virtual Requests Requests { get; set; }
    }
}
