//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rieltors.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.RequestProperties = new HashSet<RequestProperties>();
        }
    
        public int RequestID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> RealtorID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestType { get; set; }
        public string PropertyType { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> PriceMin { get; set; }
        public Nullable<decimal> PriceMax { get; set; }
        public Nullable<decimal> AreaMin { get; set; }
        public Nullable<decimal> AreaMax { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestProperties> RequestProperties { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
